version: '3'
services:
  web:
    build: .
    ports:
      - "5001:5001"
    env_file:
      - .env
    volumes:
      # Used for dev, will be commented for prod
      - ./backend:/app/backend
      - ./frontend:/app/frontend
    environment:
      - FLASK_ENV=development
      - FLASK_APP=backend/app.py
    command: python3 backend/app.py